config/routes.rb
LogstasherDemo::Application.routes.draw do
  resources :logstashes
  root to: 'logstashes#index' 

end

app/models/logstash.rb
class Logstash < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/logstashes_controller.rb
class LogstashesController < ApplicationController
  # GET /logstashes
  # GET /logstashes.json
  def index
    @logstashes = Logstash.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @logstashes }
    end
  end

  # GET /logstashes/1
  # GET /logstashes/1.json
  def show
    @logstash = Logstash.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @logstash }
    end
  end

  # GET /logstashes/new
  # GET /logstashes/new.json
  def new
    @logstash = Logstash.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @logstash }
    end
  end

  # GET /logstashes/1/edit
  def edit
    @logstash = Logstash.find(params[:id])
  end

  # POST /logstashes
  # POST /logstashes.json
  def create
    @logstash = Logstash.new(params[:logstash])

    respond_to do |format|
      if @logstash.save
        format.html { redirect_to @logstash, notice: 'Logstash was successfully created.' }
        format.json { render json: @logstash, status: :created, location: @logstash }
      else
        format.html { render action: "new" }
        format.json { render json: @logstash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /logstashes/1
  # PUT /logstashes/1.json
  def update
    @logstash = Logstash.find(params[:id])

    respond_to do |format|
      if @logstash.update_attributes(params[:logstash])
        format.html { redirect_to @logstash, notice: 'Logstash was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @logstash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logstashes/1
  # DELETE /logstashes/1.json
  def destroy
    @logstash = Logstash.find(params[:id])
    @logstash.destroy

    respond_to do |format|
      format.html { redirect_to logstashes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logstashes_helper.rb
module LogstashesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LogstasherDemo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logstashes/_form.html.erb
<%= form_for(@logstash) do |f| %>
  <% if @logstash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@logstash.errors.count, "error") %> prohibited this logstash from being saved:</h2>

      <ul>
      <% @logstash.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logstashes/edit.html.erb
<h1>Editing logstash</h1>

<%= render 'form' %>

<%= link_to 'Show', @logstash %> |
<%= link_to 'Back', logstashes_path %>

app/views/logstashes/index.html.erb
<h1>Listing logstashes</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @logstashes.each do |logstash| %>
  <tr>
    <td><%= link_to 'Show', logstash %></td>
    <td><%= link_to 'Edit', edit_logstash_path(logstash) %></td>
    <td><%= link_to 'Destroy', logstash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Logstash', new_logstash_path %>

app/views/logstashes/new.html.erb
<h1>New logstash</h1>

<%= render 'form' %>

<%= link_to 'Back', logstashes_path %>

app/views/logstashes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_logstash_path(@logstash) %> |
<%= link_to 'Back', logstashes_path %>